#pragma once

#define IO_RESTORE_ORIGINAL_DRIVERCONTROL CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1010, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_READ_VIRTUAL_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x2020, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_WRITE_VIRTUAL_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x3030, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

typedef struct _KERNEL_MEMORY_REQUEST {
	ULONG pid;
	PVOID source;
	PVOID buffer;
	SIZE_T size;
} KERNEL_MEMORY_REQUEST, * PKERNEL_MEMORY_REQUEST;
